### ISSUE TITLE
parse header file of sdl to generate correct bindings

### ISSUE THREAD

**Issue by jingkaimori** [smack0007/deno-sdl2-ffi#12]
https://github.com/libsdl-org/SDL/tree/SDL2/include

**Comment by smack0007** [comment]
I've written a script already `tools/codegen-scraper.ts` that will parse all the `SDL*.h` files and spits out enums, functions, structs, etc. to stdout. This could probably be modified now to update the generator input files (`tools/codegen/SDL/*.ts`) instead of writing to stdout. It used to be that the codegen expected a single type for certain things but now that is no longer the case and now the type given to the codegen is the type specified in the SDL header.

This isn't my first bindings project. See [GLFWDotNet](https://github.com/smack0007/GLFWDotNet), [GLDotNet](https://github.com/smack0007/GLDotNet), and [GLESDotNet](https://github.com/smack0007/GLESDotNet) and my experience tells me that having the in between format for the codgen input is a good idea. Generating the TS code directly from the header files is a no go for me.

Also the scraper doesn't do the SDL_image or SDL_ttf. No idea how much work that would be to make that work.
